-- Default locale

GT_CONFIG_TITLE              = "Налоги гильдии"
GT_CONFIG_TAXES_TITLE        = "Настройки налогообложения"
GT_CONFIG_TAXES_RANGE        = "Процентная ставка"
GT_CONFIG_TAXES_RANGE_DESC   = "Процент от суммы всего лута, который будет начисляться для оплаты в банк гильдии"
GT_CONFIG_TAXES_AUTOPAY      = "Платить автоматически"
GT_CONFIG_TAXES_AUTOPAY_DESC = "Оплата налогов будет происходить автоматически при открытии банка гильдии"
GT_CONFIG_LOGGING_TITLE      = "Настройки чата"
GT_CONFIG_LOGGING_LOG        = "Печать начислений"
GT_CONFIG_LOGGING_LOG_DESC   = "Начисления налогов с каждого лута будут печататься в чат"
GT_CONFIG_VERBOSE_LOG        = "Информация от согильдейцев"
GT_CONFIG_VERBOSE_LOG_DESC   = "В чат будет печататься информация о транзакциях согильдейцев"
GT_CONFIG_DEBUG_LOG          = "Отладка"
GT_CONFIG_DEBUG_LOG_DESC     = "Печать отладочной информации (для разработчиков)"

GT_GUI_TITLE                 = "Налоги гильдии"
GT_GUI_ALL_PAYED             = "Всё оплачено"
GT_GUI_TAX                   = "Начислено %s"
GT_GUI_GENERAL_INFO          = ", платим |cffffff00%i%%|r в гильдию |cffffff00%s|r"

GT_CHAT_PREFIX               = "Налоги"
GT_CHAT_GENERAL_INFO         = "Платим |cffffff00%i%%|r налогов в гильдию |cffffff00%s|r@|cffffff00%s|r"
GT_CHAT_TAX                  = "Начислено налогов: %s"
GT_CHAT_TAX_CLICK            = "Нажмите для оплаты"
GT_CHAT_ALL_PAYED            = "Всё оплачено, спасибо!"
GT_CHAT_TRANSACTION          = "Получено %s (налог %s)"
GT_CHAT_NOTHING_TO_PAY       = "Платить ничего не нужно"
GT_CHAT_OPEN_BANK            = "Пожалуйста, откройте банк гильдии"
GT_CHAT_PAYING_TAX           = "Оплачиваю %s налога"
